// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
class CMesHead;
class CMesHeadDefaultTypeInternal;
extern CMesHeadDefaultTypeInternal _CMesHead_default_instance_;
class CMessage;
class CMessageDefaultTypeInternal;
extern CMessageDefaultTypeInternal _CMessage_default_instance_;
class CProxyHead;
class CProxyHeadDefaultTypeInternal;
extern CProxyHeadDefaultTypeInternal _CProxyHead_default_instance_;
class CProxyMessage;
class CProxyMessageDefaultTypeInternal;
extern CProxyMessageDefaultTypeInternal _CProxyMessage_default_instance_;
class CSocketInfo;
class CSocketInfoDefaultTypeInternal;
extern CSocketInfoDefaultTypeInternal _CSocketInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CMesHead* Arena::CreateMaybeMessage<::CMesHead>(Arena*);
template<> ::CMessage* Arena::CreateMaybeMessage<::CMessage>(Arena*);
template<> ::CProxyHead* Arena::CreateMaybeMessage<::CProxyHead>(Arena*);
template<> ::CProxyMessage* Arena::CreateMaybeMessage<::CProxyMessage>(Arena*);
template<> ::CSocketInfo* Arena::CreateMaybeMessage<::CSocketInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum enServerType : int {
  FE_TIMER = 0,
  FE_CLIENT = 1,
  FE_GAMESERVER = 2,
  FE_LOGINSERVER = 3,
  FE_DBSERVER = 4,
  FE_PROXYSERVER = 5,
  FE_WORLDSERVER = 6,
  FE_WEBSERVER = 7,
  FE_OFFLINESERVER = 8,
  FE_CHECKSERVER = 9,
  FE_HALLSERVER = 10,
  FE_GATESERVER = 11,
  FE_ROOMSERVER = 12
};
bool enServerType_IsValid(int value);
constexpr enServerType enServerType_MIN = FE_TIMER;
constexpr enServerType enServerType_MAX = FE_ROOMSERVER;
constexpr int enServerType_ARRAYSIZE = enServerType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* enServerType_descriptor();
template<typename T>
inline const std::string& enServerType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, enServerType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function enServerType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    enServerType_descriptor(), enum_t_value);
}
inline bool enServerType_Parse(
    const std::string& name, enServerType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<enServerType>(
    enServerType_descriptor(), name, value);
}
enum enMessageCmd : int {
  MESS_NULL = 0,
  MESS_REGIST = 1,
  MESS_KEEPALIVE = 2,
  MESS_LOGIC = 3
};
bool enMessageCmd_IsValid(int value);
constexpr enMessageCmd enMessageCmd_MIN = MESS_NULL;
constexpr enMessageCmd enMessageCmd_MAX = MESS_LOGIC;
constexpr int enMessageCmd_ARRAYSIZE = enMessageCmd_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* enMessageCmd_descriptor();
template<typename T>
inline const std::string& enMessageCmd_Name(T enum_t_value) {
  static_assert(::std::is_same<T, enMessageCmd>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function enMessageCmd_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    enMessageCmd_descriptor(), enum_t_value);
}
inline bool enMessageCmd_Parse(
    const std::string& name, enMessageCmd* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<enMessageCmd>(
    enMessageCmd_descriptor(), name, value);
}
// ===================================================================

class CSocketInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CSocketInfo) */ {
 public:
  CSocketInfo();
  virtual ~CSocketInfo();

  CSocketInfo(const CSocketInfo& from);
  CSocketInfo(CSocketInfo&& from) noexcept
    : CSocketInfo() {
    *this = ::std::move(from);
  }

  inline CSocketInfo& operator=(const CSocketInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline CSocketInfo& operator=(CSocketInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CSocketInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CSocketInfo* internal_default_instance() {
    return reinterpret_cast<const CSocketInfo*>(
               &_CSocketInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CSocketInfo* other);
  friend void swap(CSocketInfo& a, CSocketInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CSocketInfo* New() const final {
    return CreateMaybeMessage<CSocketInfo>(nullptr);
  }

  CSocketInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CSocketInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CSocketInfo& from);
  void MergeFrom(const CSocketInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CSocketInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CSocketInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 createTime = 2;
  bool has_createtime() const;
  void clear_createtime();
  static const int kCreateTimeFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int64 createtime() const;
  void set_createtime(::PROTOBUF_NAMESPACE_ID::int64 value);

  // optional int32 socketID = 1;
  bool has_socketid() const;
  void clear_socketid();
  static const int kSocketIDFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 socketid() const;
  void set_socketid(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional int32 state = 3;
  bool has_state() const;
  void clear_state();
  static const int kStateFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::int32 state() const;
  void set_state(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:CSocketInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int64 createtime_;
  ::PROTOBUF_NAMESPACE_ID::int32 socketid_;
  ::PROTOBUF_NAMESPACE_ID::int32 state_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class CMesHead :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMesHead) */ {
 public:
  CMesHead();
  virtual ~CMesHead();

  CMesHead(const CMesHead& from);
  CMesHead(CMesHead&& from) noexcept
    : CMesHead() {
    *this = ::std::move(from);
  }

  inline CMesHead& operator=(const CMesHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMesHead& operator=(CMesHead&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CMesHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CMesHead* internal_default_instance() {
    return reinterpret_cast<const CMesHead*>(
               &_CMesHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CMesHead* other);
  friend void swap(CMesHead& a, CMesHead& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CMesHead* New() const final {
    return CreateMaybeMessage<CMesHead>(nullptr);
  }

  CMesHead* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CMesHead>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CMesHead& from);
  void MergeFrom(const CMesHead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMesHead* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMesHead";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .CSocketInfo socketInfos = 2;
  int socketinfos_size() const;
  void clear_socketinfos();
  static const int kSocketInfosFieldNumber = 2;
  ::CSocketInfo* mutable_socketinfos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CSocketInfo >*
      mutable_socketinfos();
  const ::CSocketInfo& socketinfos(int index) const;
  ::CSocketInfo* add_socketinfos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CSocketInfo >&
      socketinfos() const;

  // required .enMessageCmd opFlag = 1 [default = MESS_NULL];
  bool has_opflag() const;
  void clear_opflag();
  static const int kOpFlagFieldNumber = 1;
  ::enMessageCmd opflag() const;
  void set_opflag(::enMessageCmd value);

  // optional int32 cmd = 3;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::int32 cmd() const;
  void set_cmd(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional int32 serial = 4;
  bool has_serial() const;
  void clear_serial();
  static const int kSerialFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::int32 serial() const;
  void set_serial(::PROTOBUF_NAMESPACE_ID::int32 value);

  // optional int32 seq = 5;
  bool has_seq() const;
  void clear_seq();
  static const int kSeqFieldNumber = 5;
  ::PROTOBUF_NAMESPACE_ID::int32 seq() const;
  void set_seq(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:CMesHead)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CSocketInfo > socketinfos_;
  int opflag_;
  ::PROTOBUF_NAMESPACE_ID::int32 cmd_;
  ::PROTOBUF_NAMESPACE_ID::int32 serial_;
  ::PROTOBUF_NAMESPACE_ID::int32 seq_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class CMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMessage) */ {
 public:
  CMessage();
  virtual ~CMessage();

  CMessage(const CMessage& from);
  CMessage(CMessage&& from) noexcept
    : CMessage() {
    *this = ::std::move(from);
  }

  inline CMessage& operator=(const CMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMessage& operator=(CMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CMessage* internal_default_instance() {
    return reinterpret_cast<const CMessage*>(
               &_CMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(CMessage* other);
  friend void swap(CMessage& a, CMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CMessage* New() const final {
    return CreateMaybeMessage<CMessage>(nullptr);
  }

  CMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CMessage& from);
  void MergeFrom(const CMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .CMesHead msgHead = 1;
  bool has_msghead() const;
  void clear_msghead();
  static const int kMsgHeadFieldNumber = 1;
  const ::CMesHead& msghead() const;
  ::CMesHead* release_msghead();
  ::CMesHead* mutable_msghead();
  void set_allocated_msghead(::CMesHead* msghead);

  // required fixed64 msgPara = 2 [default = 0];
  bool has_msgpara() const;
  void clear_msgpara();
  static const int kMsgParaFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint64 msgpara() const;
  void set_msgpara(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:CMessage)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::CMesHead* msghead_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msgpara_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class CProxyHead :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CProxyHead) */ {
 public:
  CProxyHead();
  virtual ~CProxyHead();

  CProxyHead(const CProxyHead& from);
  CProxyHead(CProxyHead&& from) noexcept
    : CProxyHead() {
    *this = ::std::move(from);
  }

  inline CProxyHead& operator=(const CProxyHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline CProxyHead& operator=(CProxyHead&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CProxyHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CProxyHead* internal_default_instance() {
    return reinterpret_cast<const CProxyHead*>(
               &_CProxyHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(CProxyHead* other);
  friend void swap(CProxyHead& a, CProxyHead& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CProxyHead* New() const final {
    return CreateMaybeMessage<CProxyHead>(nullptr);
  }

  CProxyHead* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CProxyHead>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CProxyHead& from);
  void MergeFrom(const CProxyHead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CProxyHead* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CProxyHead";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CMesHead msgHead = 8;
  bool has_msghead() const;
  void clear_msghead();
  static const int kMsgHeadFieldNumber = 8;
  const ::CMesHead& msghead() const;
  ::CMesHead* release_msghead();
  ::CMesHead* mutable_msghead();
  void set_allocated_msghead(::CMesHead* msghead);

  // required uint32 srcFE = 1;
  bool has_srcfe() const;
  void clear_srcfe();
  static const int kSrcFEFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint32 srcfe() const;
  void set_srcfe(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // required uint32 srcID = 2;
  bool has_srcid() const;
  void clear_srcid();
  static const int kSrcIDFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint32 srcid() const;
  void set_srcid(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // required uint32 dstFE = 3;
  bool has_dstfe() const;
  void clear_dstfe();
  static const int kDstFEFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::uint32 dstfe() const;
  void set_dstfe(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // required uint32 dstID = 4;
  bool has_dstid() const;
  void clear_dstid();
  static const int kDstIDFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::uint32 dstid() const;
  void set_dstid(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // required uint64 timeStamp = 5;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimeStampFieldNumber = 5;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // optional .enMessageCmd opFlag = 6 [default = MESS_NULL];
  bool has_opflag() const;
  void clear_opflag();
  static const int kOpFlagFieldNumber = 6;
  ::enMessageCmd opflag() const;
  void set_opflag(::enMessageCmd value);

  // optional uint32 messageId = 7;
  bool has_messageid() const;
  void clear_messageid();
  static const int kMessageIdFieldNumber = 7;
  ::PROTOBUF_NAMESPACE_ID::uint32 messageid() const;
  void set_messageid(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:CProxyHead)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::CMesHead* msghead_;
  ::PROTOBUF_NAMESPACE_ID::uint32 srcfe_;
  ::PROTOBUF_NAMESPACE_ID::uint32 srcid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 dstfe_;
  ::PROTOBUF_NAMESPACE_ID::uint32 dstid_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  int opflag_;
  ::PROTOBUF_NAMESPACE_ID::uint32 messageid_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class CProxyMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CProxyMessage) */ {
 public:
  CProxyMessage();
  virtual ~CProxyMessage();

  CProxyMessage(const CProxyMessage& from);
  CProxyMessage(CProxyMessage&& from) noexcept
    : CProxyMessage() {
    *this = ::std::move(from);
  }

  inline CProxyMessage& operator=(const CProxyMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline CProxyMessage& operator=(CProxyMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CProxyMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CProxyMessage* internal_default_instance() {
    return reinterpret_cast<const CProxyMessage*>(
               &_CProxyMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(CProxyMessage* other);
  friend void swap(CProxyMessage& a, CProxyMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CProxyMessage* New() const final {
    return CreateMaybeMessage<CProxyMessage>(nullptr);
  }

  CProxyMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CProxyMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CProxyMessage& from);
  void MergeFrom(const CProxyMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CProxyMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CProxyMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_message_2eproto);
    return ::descriptor_table_message_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .CProxyHead msgHead = 1;
  bool has_msghead() const;
  void clear_msghead();
  static const int kMsgHeadFieldNumber = 1;
  const ::CProxyHead& msghead() const;
  ::CProxyHead* release_msghead();
  ::CProxyHead* mutable_msghead();
  void set_allocated_msghead(::CProxyHead* msghead);

  // optional fixed64 msgPara = 2 [default = 0];
  bool has_msgpara() const;
  void clear_msgpara();
  static const int kMsgParaFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint64 msgpara() const;
  void set_msgpara(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:CProxyMessage)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::CProxyHead* msghead_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msgpara_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CSocketInfo

// optional int32 socketID = 1;
inline bool CSocketInfo::has_socketid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CSocketInfo::clear_socketid() {
  socketid_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CSocketInfo::socketid() const {
  // @@protoc_insertion_point(field_get:CSocketInfo.socketID)
  return socketid_;
}
inline void CSocketInfo::set_socketid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  socketid_ = value;
  // @@protoc_insertion_point(field_set:CSocketInfo.socketID)
}

// optional int64 createTime = 2;
inline bool CSocketInfo::has_createtime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSocketInfo::clear_createtime() {
  createtime_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 CSocketInfo::createtime() const {
  // @@protoc_insertion_point(field_get:CSocketInfo.createTime)
  return createtime_;
}
inline void CSocketInfo::set_createtime(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  createtime_ = value;
  // @@protoc_insertion_point(field_set:CSocketInfo.createTime)
}

// optional int32 state = 3;
inline bool CSocketInfo::has_state() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CSocketInfo::clear_state() {
  state_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CSocketInfo::state() const {
  // @@protoc_insertion_point(field_get:CSocketInfo.state)
  return state_;
}
inline void CSocketInfo::set_state(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  state_ = value;
  // @@protoc_insertion_point(field_set:CSocketInfo.state)
}

// -------------------------------------------------------------------

// CMesHead

// required .enMessageCmd opFlag = 1 [default = MESS_NULL];
inline bool CMesHead::has_opflag() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMesHead::clear_opflag() {
  opflag_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::enMessageCmd CMesHead::opflag() const {
  // @@protoc_insertion_point(field_get:CMesHead.opFlag)
  return static_cast< ::enMessageCmd >(opflag_);
}
inline void CMesHead::set_opflag(::enMessageCmd value) {
  assert(::enMessageCmd_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  opflag_ = value;
  // @@protoc_insertion_point(field_set:CMesHead.opFlag)
}

// repeated .CSocketInfo socketInfos = 2;
inline int CMesHead::socketinfos_size() const {
  return socketinfos_.size();
}
inline void CMesHead::clear_socketinfos() {
  socketinfos_.Clear();
}
inline ::CSocketInfo* CMesHead::mutable_socketinfos(int index) {
  // @@protoc_insertion_point(field_mutable:CMesHead.socketInfos)
  return socketinfos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CSocketInfo >*
CMesHead::mutable_socketinfos() {
  // @@protoc_insertion_point(field_mutable_list:CMesHead.socketInfos)
  return &socketinfos_;
}
inline const ::CSocketInfo& CMesHead::socketinfos(int index) const {
  // @@protoc_insertion_point(field_get:CMesHead.socketInfos)
  return socketinfos_.Get(index);
}
inline ::CSocketInfo* CMesHead::add_socketinfos() {
  // @@protoc_insertion_point(field_add:CMesHead.socketInfos)
  return socketinfos_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CSocketInfo >&
CMesHead::socketinfos() const {
  // @@protoc_insertion_point(field_list:CMesHead.socketInfos)
  return socketinfos_;
}

// optional int32 cmd = 3;
inline bool CMesHead::has_cmd() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMesHead::clear_cmd() {
  cmd_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CMesHead::cmd() const {
  // @@protoc_insertion_point(field_get:CMesHead.cmd)
  return cmd_;
}
inline void CMesHead::set_cmd(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  cmd_ = value;
  // @@protoc_insertion_point(field_set:CMesHead.cmd)
}

// optional int32 serial = 4;
inline bool CMesHead::has_serial() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMesHead::clear_serial() {
  serial_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CMesHead::serial() const {
  // @@protoc_insertion_point(field_get:CMesHead.serial)
  return serial_;
}
inline void CMesHead::set_serial(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  serial_ = value;
  // @@protoc_insertion_point(field_set:CMesHead.serial)
}

// optional int32 seq = 5;
inline bool CMesHead::has_seq() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMesHead::clear_seq() {
  seq_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CMesHead::seq() const {
  // @@protoc_insertion_point(field_get:CMesHead.seq)
  return seq_;
}
inline void CMesHead::set_seq(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  seq_ = value;
  // @@protoc_insertion_point(field_set:CMesHead.seq)
}

// -------------------------------------------------------------------

// CMessage

// required .CMesHead msgHead = 1;
inline bool CMessage::has_msghead() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMessage::clear_msghead() {
  if (msghead_ != nullptr) msghead_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::CMesHead& CMessage::msghead() const {
  const ::CMesHead* p = msghead_;
  // @@protoc_insertion_point(field_get:CMessage.msgHead)
  return p != nullptr ? *p : *reinterpret_cast<const ::CMesHead*>(
      &::_CMesHead_default_instance_);
}
inline ::CMesHead* CMessage::release_msghead() {
  // @@protoc_insertion_point(field_release:CMessage.msgHead)
  _has_bits_[0] &= ~0x00000001u;
  ::CMesHead* temp = msghead_;
  msghead_ = nullptr;
  return temp;
}
inline ::CMesHead* CMessage::mutable_msghead() {
  _has_bits_[0] |= 0x00000001u;
  if (msghead_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMesHead>(GetArenaNoVirtual());
    msghead_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CMessage.msgHead)
  return msghead_;
}
inline void CMessage::set_allocated_msghead(::CMesHead* msghead) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete msghead_;
  }
  if (msghead) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msghead = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msghead, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  msghead_ = msghead;
  // @@protoc_insertion_point(field_set_allocated:CMessage.msgHead)
}

// required fixed64 msgPara = 2 [default = 0];
inline bool CMessage::has_msgpara() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMessage::clear_msgpara() {
  msgpara_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CMessage::msgpara() const {
  // @@protoc_insertion_point(field_get:CMessage.msgPara)
  return msgpara_;
}
inline void CMessage::set_msgpara(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  msgpara_ = value;
  // @@protoc_insertion_point(field_set:CMessage.msgPara)
}

// -------------------------------------------------------------------

// CProxyHead

// required uint32 srcFE = 1;
inline bool CProxyHead::has_srcfe() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CProxyHead::clear_srcfe() {
  srcfe_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CProxyHead::srcfe() const {
  // @@protoc_insertion_point(field_get:CProxyHead.srcFE)
  return srcfe_;
}
inline void CProxyHead::set_srcfe(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  srcfe_ = value;
  // @@protoc_insertion_point(field_set:CProxyHead.srcFE)
}

// required uint32 srcID = 2;
inline bool CProxyHead::has_srcid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CProxyHead::clear_srcid() {
  srcid_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CProxyHead::srcid() const {
  // @@protoc_insertion_point(field_get:CProxyHead.srcID)
  return srcid_;
}
inline void CProxyHead::set_srcid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  srcid_ = value;
  // @@protoc_insertion_point(field_set:CProxyHead.srcID)
}

// required uint32 dstFE = 3;
inline bool CProxyHead::has_dstfe() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CProxyHead::clear_dstfe() {
  dstfe_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CProxyHead::dstfe() const {
  // @@protoc_insertion_point(field_get:CProxyHead.dstFE)
  return dstfe_;
}
inline void CProxyHead::set_dstfe(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  dstfe_ = value;
  // @@protoc_insertion_point(field_set:CProxyHead.dstFE)
}

// required uint32 dstID = 4;
inline bool CProxyHead::has_dstid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CProxyHead::clear_dstid() {
  dstid_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CProxyHead::dstid() const {
  // @@protoc_insertion_point(field_get:CProxyHead.dstID)
  return dstid_;
}
inline void CProxyHead::set_dstid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  dstid_ = value;
  // @@protoc_insertion_point(field_set:CProxyHead.dstID)
}

// required uint64 timeStamp = 5;
inline bool CProxyHead::has_timestamp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CProxyHead::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CProxyHead::timestamp() const {
  // @@protoc_insertion_point(field_get:CProxyHead.timeStamp)
  return timestamp_;
}
inline void CProxyHead::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000020u;
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:CProxyHead.timeStamp)
}

// optional .enMessageCmd opFlag = 6 [default = MESS_NULL];
inline bool CProxyHead::has_opflag() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CProxyHead::clear_opflag() {
  opflag_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::enMessageCmd CProxyHead::opflag() const {
  // @@protoc_insertion_point(field_get:CProxyHead.opFlag)
  return static_cast< ::enMessageCmd >(opflag_);
}
inline void CProxyHead::set_opflag(::enMessageCmd value) {
  assert(::enMessageCmd_IsValid(value));
  _has_bits_[0] |= 0x00000040u;
  opflag_ = value;
  // @@protoc_insertion_point(field_set:CProxyHead.opFlag)
}

// optional uint32 messageId = 7;
inline bool CProxyHead::has_messageid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CProxyHead::clear_messageid() {
  messageid_ = 0u;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CProxyHead::messageid() const {
  // @@protoc_insertion_point(field_get:CProxyHead.messageId)
  return messageid_;
}
inline void CProxyHead::set_messageid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000080u;
  messageid_ = value;
  // @@protoc_insertion_point(field_set:CProxyHead.messageId)
}

// optional .CMesHead msgHead = 8;
inline bool CProxyHead::has_msghead() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CProxyHead::clear_msghead() {
  if (msghead_ != nullptr) msghead_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::CMesHead& CProxyHead::msghead() const {
  const ::CMesHead* p = msghead_;
  // @@protoc_insertion_point(field_get:CProxyHead.msgHead)
  return p != nullptr ? *p : *reinterpret_cast<const ::CMesHead*>(
      &::_CMesHead_default_instance_);
}
inline ::CMesHead* CProxyHead::release_msghead() {
  // @@protoc_insertion_point(field_release:CProxyHead.msgHead)
  _has_bits_[0] &= ~0x00000001u;
  ::CMesHead* temp = msghead_;
  msghead_ = nullptr;
  return temp;
}
inline ::CMesHead* CProxyHead::mutable_msghead() {
  _has_bits_[0] |= 0x00000001u;
  if (msghead_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMesHead>(GetArenaNoVirtual());
    msghead_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CProxyHead.msgHead)
  return msghead_;
}
inline void CProxyHead::set_allocated_msghead(::CMesHead* msghead) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete msghead_;
  }
  if (msghead) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msghead = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msghead, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  msghead_ = msghead;
  // @@protoc_insertion_point(field_set_allocated:CProxyHead.msgHead)
}

// -------------------------------------------------------------------

// CProxyMessage

// required .CProxyHead msgHead = 1;
inline bool CProxyMessage::has_msghead() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CProxyMessage::clear_msghead() {
  if (msghead_ != nullptr) msghead_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::CProxyHead& CProxyMessage::msghead() const {
  const ::CProxyHead* p = msghead_;
  // @@protoc_insertion_point(field_get:CProxyMessage.msgHead)
  return p != nullptr ? *p : *reinterpret_cast<const ::CProxyHead*>(
      &::_CProxyHead_default_instance_);
}
inline ::CProxyHead* CProxyMessage::release_msghead() {
  // @@protoc_insertion_point(field_release:CProxyMessage.msgHead)
  _has_bits_[0] &= ~0x00000001u;
  ::CProxyHead* temp = msghead_;
  msghead_ = nullptr;
  return temp;
}
inline ::CProxyHead* CProxyMessage::mutable_msghead() {
  _has_bits_[0] |= 0x00000001u;
  if (msghead_ == nullptr) {
    auto* p = CreateMaybeMessage<::CProxyHead>(GetArenaNoVirtual());
    msghead_ = p;
  }
  // @@protoc_insertion_point(field_mutable:CProxyMessage.msgHead)
  return msghead_;
}
inline void CProxyMessage::set_allocated_msghead(::CProxyHead* msghead) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete msghead_;
  }
  if (msghead) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msghead = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msghead, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  msghead_ = msghead;
  // @@protoc_insertion_point(field_set_allocated:CProxyMessage.msgHead)
}

// optional fixed64 msgPara = 2 [default = 0];
inline bool CProxyMessage::has_msgpara() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CProxyMessage::clear_msgpara() {
  msgpara_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CProxyMessage::msgpara() const {
  // @@protoc_insertion_point(field_get:CProxyMessage.msgPara)
  return msgpara_;
}
inline void CProxyMessage::set_msgpara(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  msgpara_ = value;
  // @@protoc_insertion_point(field_set:CProxyMessage.msgPara)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::enServerType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::enServerType>() {
  return ::enServerType_descriptor();
}
template <> struct is_proto_enum< ::enMessageCmd> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::enMessageCmd>() {
  return ::enMessageCmd_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
